services:
  - type: web
    name: payload-cms-brink
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: PAYLOAD_SECRET
        generateValue: true
      - key: DATABASE_URI
        value: file:./payload.db
      - key: NEXT_PUBLIC_SERVER_URL
        sync: false
